// vghypeman/src/App.vue
<template>
  <div id="app">
    <nav id="hi8 valign-wrapper">
      <div class="nav-wrapper">
        <a href="/home">
          <div class="left hide-on-small-only" id="VGHlogo"></div>
        </a>
        <div class="left show-on-small hide-on-med-and-up" id="VGHlogoMobile"></div>
        <form action>
          <ul id="nav-mobile" class="right">
            <li>
              <input
                id="game-entry"
                class="form-control"
                type="search"
                placeholder="Search"
                aria-label="Search"
                v-on:keyup.enter="getGame()"
              />
            </li>
            <li>
              <button class="searchBtn" type id="game-submit" v-on:click="getGame()"/>
            </li>
            <li>
              <!-- <a class="socialBtn official" href="/myprofile"></a> -->
            </li>
          </ul>
        </form>
      </div>
    </nav>
    <router-view></router-view>
  </div>
</template>

<script>
import $ from 'jquery';
// import this anywhere you want to 'Bus' data around
import { EventBus } from "./components/event-bus";  

export default {
  name: "app",
  components: {
  },
  data() {
    return {
      game: ""
    }
  },
  methods: {
    getGame: function() {
      event.preventDefault();
      this.game = $("#game-entry").val().trim();
      if (this.game == "") {
          return;
      }
      $("#game-entry").val("");
      // this.game now has game name for the API
      // passing it via 'Bus' to Pic,Twitch,Youtube
      EventBus.$emit("clicked-event", this.game);  
    }
  },
    props: {
  },
};
</script>

<style>
@import url('../public/style.css');

#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
</style>

// vghypeman/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'vghypeman'; 

}

<nav id="hi8 valign-wrapper">

  <div class="nav-wrapper">

      <a href="/home"><div class="left hide-on-small-only" id="VGHlogo"></div></a>
      <div class="left show-on-small hide-on-med-and-up" id="VGHlogoMobile"></div>
      <form action="">
          <ul id="nav-mobile" class="right">
              <li><input id="game-entry" class="form-control" type="search" placeholder="Search"
                      aria-label="Search"></li>
              <li><input class="searchBtn" type="" id="game-submit" onclick="getGame()"><!-- <a id="game-submit" href="#" type="submit" onclick="getGame()"></a> --></li>
              <li><a class="socialBtn official" href="/myprofile"></a></li>
          </ul>
      </form>
  </div>

</nav>

<router-outlet></router-outlet>
